# Site settings
email: abhijit@abhijittomar.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-84479457-1

# SEO settings
title: Blog
description: Abhijit Tomar's blog
url: "blog.abhijittomar.com"
twitter_username: 
default_img: /assets/images/student-freelancing/1200.jpg

# Profile settings
name: Abhijit Tomar
profile_img: /assets/images/profile_img.jpg
profile: Abhijit Tomar is a student at IIT Bombay. When he's not programming, he's usually out for a run or playing football.
social:
  github: https://github.com/abhijitt/
  linkedin: https://www.linkedin.com/in/abhijittomar/
  facebook: https://facebook.com/abhijit.tomar/

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
